#include "render/D3DDevice.h"

#include <iterator>
#include <string>

#include "support/Log.h"

// Byte code generated by fxc at build time. See cmake/CompileShaders.cmake.
#include "shaders/VS_Fullscreen.h"
#include "shaders/PS_NV12.h"
#include "shaders/PS_P010.h"
#include "shaders/PS_Gradient.h"

namespace livewall {
namespace {

std::weak_ptr<D3DDevice> g_shared;

}  // namespace

std::shared_ptr<D3DDevice> D3DDevice::acquire() {
    if (auto existing = g_shared.lock()) return existing;

    // Not std::make_shared: the constructor is private, and the reason it is
    // private is that a D3DDevice that failed to initialise must never escape.
    std::shared_ptr<D3DDevice> created(new D3DDevice());
    if (!created->initialise()) return nullptr;

    g_shared = created;
    return created;
}

D3DDevice::~D3DDevice() {
    if (context_) {
        // Without this the deferred destruction of the swap chains' buffers can
        // outlive the device, which the debug layer reports as a leak and the
        // release runtime handles by keeping the memory a little longer than it
        // should.
        context_->ClearState();
        context_->Flush();
    }
}

bool D3DDevice::initialise() {
    UINT flags = D3D11_CREATE_DEVICE_BGRA_SUPPORT |  // required by DirectComposition
                 D3D11_CREATE_DEVICE_VIDEO_SUPPORT;  // required for DXVA decode
#ifdef _DEBUG
    flags |= D3D11_CREATE_DEVICE_DEBUG;
#endif

    // 11_1 down to 10_0. Anything that runs Windows 10 clears 10_0, and the
    // shader model this app uses (5_0 features, no compute, no tessellation)
    // is available on all of them.
    static const D3D_FEATURE_LEVEL levels[] = {
        D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0,
        D3D_FEATURE_LEVEL_10_1, D3D_FEATURE_LEVEL_10_0,
    };

    ComPtr<ID3D11Device> baseDevice;
    ComPtr<ID3D11DeviceContext> baseContext;
    D3D_FEATURE_LEVEL achieved{};

    HRESULT hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, flags, levels,
                                   static_cast<UINT>(std::size(levels)), D3D11_SDK_VERSION,
                                   &baseDevice, &achieved, &baseContext);
#ifdef _DEBUG
    if (FAILED(hr) && (flags & D3D11_CREATE_DEVICE_DEBUG) != 0) {
        // The debug layer is a separate optional Windows feature, and its
        // absence is a confusing E_FAIL rather than anything that names it.
        flags &= ~static_cast<UINT>(D3D11_CREATE_DEVICE_DEBUG);
        hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, flags, levels,
                               static_cast<UINT>(std::size(levels)), D3D11_SDK_VERSION,
                               &baseDevice, &achieved, &baseContext);
    }
#endif
    if (FAILED(hr)) {
        Log::error("D3D11CreateDevice failed: " + Log::hresult(hr));
        return false;
    }

    if (FAILED(baseDevice.As(&device_)) || FAILED(baseContext.As(&context_))) {
        Log::error("this driver does not expose the ID3D11Device1 interface");
        return false;
    }

    // Each monitor's render thread pulls and draws a frame while the UI thread
    // may be resizing a swap chain. Without this the runtime applies no
    // serialisation of its own and the two race inside the immediate context.
    //
    // This makes individual calls safe, not sequences of them — see
    // `lockFrame()` for the part that covers a whole frame.
    ComPtr<ID3D11Multithread> multithread;
    if (SUCCEEDED(device_.As(&multithread))) multithread->SetMultithreadProtected(TRUE);

    ComPtr<IDXGIDevice1> dxgiDevice;
    ComPtr<IDXGIAdapter> adapter;
    if (FAILED(device_.As(&dxgiDevice)) || FAILED(dxgiDevice->GetAdapter(&adapter)) ||
        FAILED(adapter->GetParent(IID_PPV_ARGS(&factory_)))) {
        Log::error("could not reach the DXGI factory from the device");
        return false;
    }

    // One frame of latency, not the default three. The whole memory argument of
    // this app is "one frame in flight"; leaving DXGI to queue three would
    // hold three decoded frames alive, and at 4K 10-bit each of those is about
    // 20 MB.
    dxgiDevice->SetMaximumFrameLatency(1);

    if (FAILED(device_->CreateVertexShader(g_VS_Fullscreen, sizeof(g_VS_Fullscreen), nullptr,
                                           &fullscreenVS_)) ||
        FAILED(device_->CreatePixelShader(g_PS_NV12, sizeof(g_PS_NV12), nullptr, &nv12PS_)) ||
        FAILED(device_->CreatePixelShader(g_PS_P010, sizeof(g_PS_P010), nullptr, &p010PS_)) ||
        FAILED(device_->CreatePixelShader(g_PS_Gradient, sizeof(g_PS_Gradient), nullptr,
                                          &gradientPS_))) {
        Log::error("shader creation failed — the byte code and the driver disagree");
        return false;
    }

    D3D11_SAMPLER_DESC sampler{};
    sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_LINEAR;
    // Clamp rather than wrap: in Fill mode the quad extends past the viewport
    // and a wrapping sampler would show the opposite edge of the frame bleeding
    // in along the crop.
    sampler.AddressU = D3D11_TEXTURE_ADDRESS_CLAMP;
    sampler.AddressV = D3D11_TEXTURE_ADDRESS_CLAMP;
    sampler.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
    sampler.ComparisonFunc = D3D11_COMPARISON_NEVER;
    sampler.MaxLOD = D3D11_FLOAT32_MAX;
    if (FAILED(device_->CreateSamplerState(&sampler, &sampler_))) return false;

    D3D11_BUFFER_DESC constants{};
    constants.ByteWidth = sizeof(FrameConstants);
    constants.Usage = D3D11_USAGE_DYNAMIC;
    constants.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    constants.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    if (FAILED(device_->CreateBuffer(&constants, nullptr, &constants_))) return false;

    // Opaque source over a transparent target. The frame itself always has
    // alpha 1; what matters is that the region the quad does not cover keeps
    // the cleared, fully transparent value so DirectComposition shows the
    // user's real wallpaper through it.
    D3D11_BLEND_DESC blend{};
    blend.RenderTarget[0].BlendEnable = TRUE;
    blend.RenderTarget[0].SrcBlend = D3D11_BLEND_ONE;  // premultiplied
    blend.RenderTarget[0].DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
    blend.RenderTarget[0].BlendOp = D3D11_BLEND_OP_ADD;
    blend.RenderTarget[0].SrcBlendAlpha = D3D11_BLEND_ONE;
    blend.RenderTarget[0].DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
    blend.RenderTarget[0].BlendOpAlpha = D3D11_BLEND_OP_ADD;
    blend.RenderTarget[0].RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    if (FAILED(device_->CreateBlendState(&blend, &blend_))) return false;

    D3D11_RASTERIZER_DESC raster{};
    raster.FillMode = D3D11_FILL_SOLID;
    // No culling: the full-screen triangle's winding depends on nothing, and a
    // negative fit scale would flip it.
    raster.CullMode = D3D11_CULL_NONE;
    raster.DepthClipEnable = TRUE;
    if (FAILED(device_->CreateRasterizerState(&raster, &rasteriser_))) return false;

    Log::info("D3D11 device created at feature level " +
              std::to_string((achieved >> 12) & 0xF) + "." +
              std::to_string((achieved >> 8) & 0xF));
    return true;
}

void D3DDevice::bindPipeline(const FrameConstants& values) {
    D3D11_MAPPED_SUBRESOURCE mapped{};
    if (SUCCEEDED(context_->Map(constants_.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
        *static_cast<FrameConstants*>(mapped.pData) = values;
        context_->Unmap(constants_.Get(), 0);
    }

    // No input layout and no vertex buffer: the vertex shader builds the
    // triangle from SV_VertexID.
    context_->IASetInputLayout(nullptr);
    context_->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    context_->VSSetShader(fullscreenVS_.Get(), nullptr, 0);
    context_->VSSetConstantBuffers(0, 1, constants_.GetAddressOf());
    context_->PSSetConstantBuffers(0, 1, constants_.GetAddressOf());
    context_->PSSetSamplers(0, 1, sampler_.GetAddressOf());
    context_->RSSetState(rasteriser_.Get());

    const float blendFactor[4] = {0, 0, 0, 0};
    context_->OMSetBlendState(blend_.Get(), blendFactor, 0xFFFFFFFF);
}

bool D3DDevice::isLost() const {
    if (!device_) return true;
    const HRESULT reason = device_->GetDeviceRemovedReason();
    return reason != S_OK;
}

}  // namespace livewall
